#!/bin/sh

# Generates coverage report

# lcov must be installed
# run this script after compiling tests with COVERAGE=ON
# the output is in build-coverage/index.html

make clean clean-coverage
make -j8
lcov -c -i -d . -o initial-coverage.info
bin/unittests
lcov -c -d . -o test-coverage.info
lcov -a initial-coverage.info -a test-coverage.info -o coverage.info
lcov -r coverage.info "ext/src/q*" -o coverage.info
lcov -r coverage.info "/usr/*" -o coverage.info
lcov -r coverage.info "test/*" -o coverage.info
genhtml coverage.info -o build-coverage -s -p `pwd` --highlight --demangle-cpp
rm *coverage.info
