//--------------------------------------------------------------------*- C++ -*-
//
//  Qore Programming Language
//
//  Copyright (C) 2015 Qore Technologies
//
//  Permission is hereby granted, free of charge, to any person obtaining a
//  copy of this software and associated documentation files (the "Software"),
//  to deal in the Software without restriction, including without limitation
//  the rights to use, copy, modify, merge, publish, distribute, sublicense,
//  and/or sell copies of the Software, and to permit persons to whom the
//  Software is furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//
//------------------------------------------------------------------------------

TOK(EndOfFile)
TOK(ParseDirective)
TOK(KwAbstract)
TOK(KwBackground)
TOK(KwCast)
TOK(KwChomp)
TOK(KwClass)
TOK(KwConst)
TOK(KwDelete)
TOK(KwDeprecated)
TOK(KwElements)
TOK(KwExists)
TOK(KwFalse)
TOK(KwFinal)
TOK(KwInstanceof)
TOK(KwKeys)
TOK(KwNamespace)
TOK(KwNew)
TOK(KwNothing)
TOK(KwNull)
TOK(KwOur)
TOK(KwPop)
TOK(KwPrivate)
TOK(KwPublic)
TOK(KwRemove)
TOK(KwSelf)
TOK(KwShift)
TOK(KwStatic)
TOK(KwSub)
TOK(KwSynchronized)
TOK(KwTrim)
TOK(KwTrue)

TOK(Ampersand)
TOK(AngleLeft)
TOK(AngleLeftAngleRight)
TOK(AngleLeftEquals)
TOK(AngleLeftEqualsAngleRight)
TOK(AngleRight)
TOK(AngleRightEquals)
TOK(Asterisk)
TOK(Backslash)
TOK(Caret)
TOK(Colon)
TOK(Comma)
TOK(CurlyLeft)
TOK(CurlyRight)
TOK(Dot)
TOK(DoubleAmpersand)
TOK(DoubleAngleLeft)
TOK(DoubleAngleRight)
TOK(DoubleColon)
TOK(DoubleEquals)
TOK(DoubleMinus)
TOK(DoublePlus)
TOK(DoubleQuestion)
TOK(DoubleVerticalBar)
TOK(Equals)
TOK(Exclamation)
TOK(ExclamationDoubleEquals)
TOK(ExclamationEquals)
TOK(Identifier)
TOK(Integer)
TOK(Minus)
TOK(ParenLeft)
TOK(ParenRight)
TOK(Percent)
TOK(Plus)
TOK(Question)
TOK(QuestionAsterisk)
TOK(Semicolon)
TOK(Slash)
TOK(SquareLeft)
TOK(SquareRight)
TOK(Tilde)
TOK(TripleEquals)
TOK(VerticalBar)

TOK(KwCatch)
TOK(KwElse)
TOK(KwIf)
TOK(KwMy)
TOK(KwPrint)
TOK(KwTry)
TOK(String)
