//--------------------------------------------------------------------*- C++ -*-
//
//  Qore Programming Language
//
//  Copyright (C) 2015 Qore Technologies
//
//  Permission is hereby granted, free of charge, to any person obtaining a
//  copy of this software and associated documentation files (the "Software"),
//  to deal in the Software without restriction, including without limitation
//  the rights to use, copy, modify, merge, publish, distribute, sublicense,
//  and/or sell copies of the Software, and to permit persons to whom the
//  Software is furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//
//------------------------------------------------------------------------------

TOK(EndOfFile)
TOK(ParseDirective)
TOK(KwAbstract)
TOK(KwClass)
TOK(KwConst)
TOK(KwDeprecated)
TOK(KwFalse)
TOK(KwFinal)
TOK(KwNamespace)
TOK(KwNothing)
TOK(KwNull)
TOK(KwOur)
TOK(KwPrivate)
TOK(KwPublic)
TOK(KwSelf)
TOK(KwStatic)
TOK(KwSub)
TOK(KwSynchronized)
TOK(KwTrue)

TOK(Asterisk)
TOK(Colon)
TOK(Comma)
TOK(CurlyLeft)
TOK(CurlyRight)
TOK(DoubleColon)
TOK(Equals)
TOK(Identifier)
TOK(Integer)
TOK(ParenLeft)
TOK(ParenRight)
TOK(Percent)
TOK(Plus)
TOK(Semicolon)
TOK(Slash)

TOK(KwCatch)
TOK(KwElse)
TOK(KwIf)
TOK(KwMy)
TOK(KwPrint)
TOK(KwTrim)
TOK(KwTry)
TOK(String)
